name: mifare_nfc_classic
description: A new Flutter plugin.
version: 0.2.1
homepage: https://github.com/MaldonadoAndres/mifare_nfc_classic

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.mifare_nfc_classic
        pluginClass: MifareNfcClassicPlugin
